// jtkicker_game_sdram.v is automatically generated by JTFRAME
// Do not modify it
// Do not add it to git

`ifndef JTFRAME_COLORW
`define JTFRAME_COLORW 4
`endif

`ifndef JTFRAME_BUTTONS
`define JTFRAME_BUTTONS 2
`endif

module jtkicker_game_sdram(
    `include "jtframe_common_ports.inc"
    `include "jtframe_mem_ports.inc"
);

/* verilator lint_off WIDTH */
`ifdef JTFRAME_BA1_START
    localparam [25:0] BA1_START=`JTFRAME_BA1_START;
`endif
`ifdef JTFRAME_BA2_START
    localparam [25:0] BA2_START=`JTFRAME_BA2_START;
`endif
`ifdef JTFRAME_BA3_START
    localparam [25:0] BA3_START=`JTFRAME_BA3_START;
`endif
`ifdef JTFRAME_PROM_START
    localparam [25:0] PROM_START=`JTFRAME_PROM_START;
`endif
/* verilator lint_on WIDTH */


parameter SCR_OFFSET = `SCR_START >> 1;
parameter OBJ_OFFSET = `OBJ_START >> 1;
parameter PCM_OFFSET = `PCM_START >> 1;

`ifndef JTFRAME_IOCTL_RD
wire ioctl_ram = 0;
`endif
// Additional ports

// BRAM buses
// SDRAM buses

wire [14:2] scr_addr;
wire [31:0] scr_data;
wire        scr_cs, scr_ok;
wire [15:2] objrom_addr;
wire [31:0] objrom_data;
wire        objrom_cs, objrom_ok;
wire [15:0] pcm_addr;
wire [ 7:0] pcm_data;
wire        pcm_cs, pcm_ok;
wire [15:0] main_addr;
wire [ 7:0] main_data;
wire        main_cs, main_ok;
wire        prom_we, header;
wire [21:0] raw_addr, post_addr;
wire [25:0] pre_addr, dwnld_addr;
wire [ 7:0] post_data;
wire [15:0] raw_data;
wire        pass_io;
// Clock enable signals
wire cpu4_cen; 
wire ti1_cen; 
wire ti2_cen; 

assign pass_io = header | ioctl_ram;

jtkicker_game u_game(
    .rst        ( rst       ),
    .clk        ( clk       ),
`ifdef JTFRAME_CLK24
    .rst24      ( rst24     ),
    .clk24      ( clk24     ),
`endif
`ifdef JTFRAME_CLK48
    .rst48      ( rst48     ),
    .clk48      ( clk48     ),
`endif
    .cpu4_cen    ( cpu4_cen    ), 
    .ti1_cen    ( ti1_cen    ), 
    .ti2_cen    ( ti2_cen    ), 

    .pxl2_cen       ( pxl2_cen      ),
    .pxl_cen        ( pxl_cen       ),
    .red            ( red           ),
    .green          ( green         ),
    .blue           ( blue          ),
    .LHBL           ( LHBL          ),
    .LVBL           ( LVBL          ),
    .HS             ( HS            ),
    .VS             ( VS            ),
    // cabinet I/O
    .start_button   ( start_button  ),
    .coin_input     ( coin_input    ),
    .joystick1      ( joystick1     ),
    .joystick2      ( joystick2     ),
    `ifdef JTFRAME_4PLAYERS
    .joystick3      ( joystick3     ),
    .joystick4      ( joystick4     ),
    `endif
`ifdef JTFRAME_ANALOG
    .joyana_l1    ( joyana_l1        ),
    .joyana_l2    ( joyana_l2        ),
    `ifdef JTFRAME_ANALOG_DUAL
        .joyana_r1    ( joyana_r1        ),
        .joyana_r2    ( joyana_r2        ),
    `endif
    `ifdef JTFRAME_4PLAYERS
        .joyana_l3( joyana_l3        ),
        .joyana_l4( joyana_l4        ),
        `ifdef JTFRAME_ANALOG_DUAL
            .joyana_r3( joyana_r3        ),
            .joyana_r4( joyana_r4        ),
        `endif
    `endif
`endif
`ifdef JTFRAME_DIAL
    .dial_x         ( dial_x        ),
    .dial_y         ( dial_y        ),
`endif
    // DIP switches
    .status         ( status        ),
    .dipsw          ( dipsw         ),
    .service        ( service       ),
    .tilt           ( tilt          ),
    .dip_pause      ( dip_pause     ),
    .dip_flip       ( dip_flip      ),
    .dip_test       ( dip_test      ),
    .dip_fxlevel    ( dip_fxlevel   ),
    // Sound output
`ifdef JTFRAME_STEREO
    .snd_left       ( snd_left      ),
    .snd_right      ( snd_right     ),
`else
    .snd            ( snd           ),
`endif
    .sample         ( sample        ),
    .game_led       ( game_led      ),
    .enable_psg     ( enable_psg    ),
    .enable_fm      ( enable_fm     ),
    // Ports declared in mem.yaml
    // Memory interface - SDRAM
    .scr_addr ( scr_addr ),
    .scr_cs   ( scr_cs   ),
    .scr_ok   ( scr_ok   ),
    .scr_data ( scr_data ),
    
    .objrom_addr ( objrom_addr ),
    .objrom_cs   ( objrom_cs   ),
    .objrom_ok   ( objrom_ok   ),
    .objrom_data ( objrom_data ),
    
    .pcm_addr ( pcm_addr ),
    .pcm_cs   ( pcm_cs   ),
    .pcm_ok   ( pcm_ok   ),
    .pcm_data ( pcm_data ),
    
    .main_addr ( main_addr ),
    .main_cs   ( main_cs   ),
    .main_ok   ( main_ok   ),
    .main_data ( main_data ),
    
    // Memory interface - BRAM

    // PROM writting
    .ioctl_addr   ( ioctl_addr     ),
    .prog_addr    ( pass_io ? ioctl_addr[21:0] : raw_addr      ),
    .prog_data    ( pass_io ? ioctl_dout       : raw_data[7:0] ),
    .prog_we      ( pass_io ? ioctl_wr         : prog_we       ),
    .prog_ba      ( prog_ba        ), // prog_ba supplied in case it helps re-mapping addresses
`ifdef JTFRAME_PROM_START
    .prom_we      ( prom_we        ),
`endif
    // SDRAM address mapper during downloading
    .post_addr    ( post_addr      ),
`ifdef JTFRAME_HEADER
    .header       ( header         ),
`endif
`ifdef JTFRAME_IOCTL_RD
    .ioctl_ram    ( ioctl_ram      ),
    .ioctl_din    ( ioctl_din      ),
`endif
    // Debug
    .debug_bus    ( debug_bus      ),
    .debug_view   ( debug_view     ),
`ifdef JTFRAME_STATUS
    .st_addr      ( st_addr        ),
    .st_dout      ( st_dout        ),
`endif
`ifdef JTFRAME_LF_BUFFER
    .game_vrender( game_vrender  ),
    .game_hdump  ( game_hdump    ),
    .ln_addr     ( ln_addr       ),
    .ln_data     ( ln_data       ),
    .ln_done     ( ln_done       ),
    .ln_hs       ( ln_hs         ),
    .ln_pxl      ( ln_pxl        ),
    .ln_v        ( ln_v          ),
    .ln_we       ( ln_we         ),
`endif
    .gfx_en      ( gfx_en        )
);

assign dwnld_busy = downloading | prom_we; // prom_we is really just for sims
assign dwnld_addr = ioctl_addr;
assign prog_addr = post_addr;
assign prog_data = raw_data;

jtframe_dwnld #(
`ifdef JTFRAME_HEADER
    .HEADER    ( `JTFRAME_HEADER   ),
`endif
`ifdef JTFRAME_BA1_START
    .BA1_START ( BA1_START ),
`endif
`ifdef JTFRAME_BA2_START
    .BA2_START ( BA2_START ),
`endif
`ifdef JTFRAME_BA3_START
    .BA3_START ( BA3_START ),
`endif
`ifdef JTFRAME_PROM_START
    .PROM_START( PROM_START ),
`endif
    .SWAB      ( 0         )
) u_dwnld(
    .clk          ( clk            ),
    .downloading  ( downloading & ~ioctl_ram    ),
    .ioctl_addr   ( dwnld_addr     ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .prog_addr    ( raw_addr       ),
    .prog_data    ( raw_data       ),
    .prog_mask    ( prog_mask      ), // active low
    .prog_we      ( prog_we        ),
    .prog_rd      ( prog_rd        ),
    .prog_ba      ( prog_ba        ),
    .prom_we      ( prom_we        ),
    .header       ( header         ),
    .sdram_ack    ( prog_ack       )
);


/* verilator tracing_off */
jtframe_rom_4slots #(
    // scr
    .SLOT0_OFFSET(SCR_OFFSET[21:0]),
    .SLOT0_AW(14),
    .SLOT0_DW(32), 
    // objrom
    .SLOT1_OFFSET(OBJ_OFFSET[21:0]),
    .SLOT1_AW(15),
    .SLOT1_DW(32), 
    // pcm
    .SLOT2_OFFSET(PCM_OFFSET[21:0]),
    .SLOT2_AW(16),
    .SLOT2_DW( 8), 
    // main
    .SLOT3_AW(16),
    .SLOT3_DW( 8)
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
    ,.SLOT2_DOUBLE(1)
    ,.SLOT3_DOUBLE(1)
`endif
) u_bank0(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { scr_addr, 1'b0 } ),
    .slot0_dout  ( scr_data  ),
    .slot0_cs    ( scr_cs    ),
    .slot0_ok    ( scr_ok    ),
    
    .slot1_addr  ( { objrom_addr, 1'b0 } ),
    .slot1_dout  ( objrom_data  ),
    .slot1_cs    ( objrom_cs    ),
    .slot1_ok    ( objrom_ok    ),
    
    .slot2_addr  ( pcm_addr  ),
    .slot2_dout  ( pcm_data  ),
    .slot2_cs    ( pcm_cs    ),
    .slot2_ok    ( pcm_ok    ),
    
    .slot3_addr  ( main_addr  ),
    .slot3_dout  ( main_data  ),
    .slot3_cs    ( main_cs    ),
    .slot3_ok    ( main_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[0]  ),
    .sdram_rd    ( ba_rd[0]   ),
    .sdram_addr  ( ba0_addr   ),
    .data_dst    ( ba_dst[0]  ),
    .data_rdy    ( ba_rdy[0]  ),
    .data_read   ( data_read  )
);
assign ba_wr[0] = 0;
assign ba0_din  = 0;
assign ba0_dsn  = 3;

assign ba1_addr = 0;
assign ba_rd[1] = 0;
assign ba_wr[1] = 0;
assign ba1_dsn  = 3;
assign ba1_din  = 0;
assign ba2_addr = 0;
assign ba_rd[2] = 0;
assign ba_wr[2] = 0;
assign ba2_dsn  = 3;
assign ba2_din  = 0;
assign ba3_addr = 0;
assign ba_rd[3] = 0;
assign ba_wr[3] = 0;
assign ba3_dsn  = 3;
assign ba3_din  = 0;



// Clock enable generation
// 6144000 = 24576000*1/4 Hz from clk24
jtframe_frac_cen #(.W(3),.WC(3)) u_cen0_clk24(
    .clk    ( clk24 ),
    .n      ( 3'd1 ),
    .m      ( 3'd4 ),
    .cen    ( { ti2_cen, ti1_cen, cpu4_cen } ),
    .cenb   (              )
);

endmodule
